name: Unit tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v6
    - name: Setup java 17
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Execute coexistDebug emulator unit tests
      run: |
        ./gradlew :terminal-emulator:testCoexistDebugUnitTest --no-daemon
